kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-provisioned-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "helm3-dev-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
