apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: rocketchat-mongodb-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          # also pull image from quay.io/alberthua/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              #value: fuseim.pri/ifs
              value: ci-platform/nfs-storage
            - name: NFS_SERVER
              value: 192.168.110.162
            - name: NFS_PATH
              value: /data/k8s
              # must create subdir named namespace as basename
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.110.162
            path: /data/k8s
