apiVersion: v1
kind: Service
metadata:
  name: mongodb-internal
  labels:
    app: rocketmongo
  #annotations:
  #  service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: rocketmongo
