apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  labels:
    app: rocketmongo
  namespace: rocketchat-mongodb-app
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: rocketmongo
