apiVersion: v1
kind: Service
metadata:
  labels:
    run: myapp
  name: myapp
  namespace: app-frontend
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
