apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-18T13:36:41Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "2719744"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 329c3866-17d9-4a49-93aa-dfaa890b1a4d
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
