apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wp
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: services.lab.example.com
    path: /exports/wordpress
